### ISSUE TITLE
feat: Add heatmap-cartesian

### ISSUE THREAD

**Issue by lcmgh** [yuankunzhang/charming#10]
I would love to have this heatmap: https://echarts.apache.org/examples/en/editor.html?c=heatmap-cartesian

**Comment by yuankunzhang** [comment]
Please refer to this example:

https://github.com/yuankunzhang/charming/blob/main/img/heatmap/heatmap_on_cartesian.svg
https://github.com/yuankunzhang/charming/blob/main/gallery/src/heatmap/heatmap_on_cartesian.rs
