### ISSUE TITLE
AxisLabel - no font-weight, no font-family?

### ISSUE THREAD

**Issue by tower120** [yuankunzhang/charming#111]
Is it possible to set font weight and font family for labels on axis? I see only font-size setting.

**Comment by LukaOber** [comment]
I will try to open a PR this weekend to add this functionality.

**Comment by LukaOber** [comment]
Latest master should have the changes you want. Let me know if you are having any problems or questions.

**Comment by tower120** [comment]
I just tried that. It works. Thanks!

But you know, all text on "png" saved files looks blurry. It is OK for >=16 size font - but everything bellow is hard to read.
It looks like text in old versions of Chrome... When they used SDF fonts.
Maybe there is no sub-pixel anti-aliasing in png renderer? Or something like this...
