### ISSUE TITLE
xAxis start_value option missing

### ISSUE THREAD

**Issue by tqwewe** [yuankunzhang/charming#113]
Looking at the docs for ECharts, it seems like there should be an option for xAxis `startValue`, which doesn't seem to exist in this library.
<https://echarts.apache.org/en/option.html#xAxis.startValue>

I guess this is a relatively new option in ECharts 5.5.1, and I'm not quite sure what version of ECharts charming supports currently.

**Comment by LukaOber** [comment]
We are currently running 5.5.0, an upgrade to 5.5.1 was not possible last time as the cdn we used only had 5.5.0. I will check it again and potentially open a PR next week. 

The option `startValue` would then need to be implemented, but that should be fairly trivial. 

I will keep you updated
