### ISSUE TITLE
Large candlestick charts not fully plotting

### ISSUE THREAD

**Issue by pferreira8** [yuankunzhang/charming#17]
I have converted some polars dataframes into the underlying Vec<f64> types to pass into the charming df! macro and managed to build a working pipeline for making charts.
Running into an issue with a chart that starts from YTD for daily bars, and it compiles and saves the data into an html file.
When it comes to opening the file in the web browser it only renders a few bars and then nothing more. Even though the date axis and raw html data is fully available in the file. 

Any leads on what I can try changing? 
![Screenshot 2023-08-07 234453](https://github.com/yuankunzhang/charming/assets/60457808/814b722e-d32e-4500-905e-3181b81c4594)

![Screenshot 2023-08-07 231754](https://github.com/yuankunzhang/charming/assets/60457808/e3536096-85a5-4e17-9990-ac52b1fd0e5d)

[test_data.txt](https://github.com/yuankunzhang/charming/files/12286994/test_data.txt)

**Comment by pferreira8** [comment]
the txt file is a raw copy of my html file

**Comment by yuankunzhang** [comment]
Hi @pferreira8 , thanks for reporting the issue. For sure I'll need to add more docs on how to feed data into the charts.

In your code, the `df![]` macro creates a vector with four nested vectors, in this shape:

```
[
  [d_open0, d_open1, ...],
  [d_high0, d_high1, ...],
  [d_low0, d_low1, ...],
  [d_close0, d_close1, ...]
]
```

But the shape of the vector we need here is like:

```
[
  [d_open0, d_high0, d_low0, d_close0],
  [d_open1, d_high1, d_low1, d_close1],
  ...
]
```

So we don't really need to use the `df[]` macro here, just construct a vector of `[d_open, d_high, d_low, d_close]` and pass the vector to the data method.

Let me know if this helps.

**Comment by pferreira8** [comment]
thank you for the fast reply and in fact I have got it working now that I have the shape fitted properly! 
This crate is a great step in adding more visualization tools for rust developers, I would be glad to help out with documenting the codebase or adding features if there are any in particular that are under consideration.

**Comment by pferreira8** [comment]
I have now called the color_by method using both the ColorBy::Series or ColorBy::Data enums but that didn't alter the coloring since I am only getting red colored bars. I assume I am just overlooking something simple.

**Comment by yuankunzhang** [comment]
Can you please provide the partial code snippet you were using? I'll take a look later.

**Comment by pferreira8** [comment]
```
        let chart = Chart::new()
            .x_axis(Axis::new().show(true).data(dt))
            .y_axis(Axis::new().show(true).scale(true))
            .data_zoom(
                DataZoom::new()
                    .type_(DataZoomType::Slider)
                    .start(50)
                    .end(100)
                    .min_value_span(10),
            )
            .series(Candlestick::new().data(
                ohlc_vec
            ))
	    .background_color("6E7468")
	    .color_by(ColorBy::Data);

        Ok(chart)
    }

```

**Comment by pferreira8** [comment]
was no need for me to re-open the issue actually since my main issue has been resolved
