### ISSUE TITLE
can't zoom by mouse

### ISSUE THREAD

**Issue by Fred0327** [yuankunzhang/charming#18]
In JavaScript, if an image is too large, we can use mouse movements to pan and zoom the image. However, this is not possible in charming.

**Comment by yuankunzhang** [comment]
Hi @Fred0327 , can you post the code snippet you were using?

**Comment by Fred0327** [comment]
I forked and created a new branch [dev](https://github.com/Fred0327/charming/tree/dev), you can run the `dioxus-web-demo ` in the example dir. 

The js example is [here](https://echarts.apache.org/examples/zh/editor.html?c=candlestick-sh-2015), you can use mouse zoom and pan the candlesticks.

**Comment by yuankunzhang** [comment]
There's this [DataZoom](charming/src/component/data_zoom.rs) component that can be used for zooming.
