### ISSUE TITLE
Line with label is not supported?

### ISSUE THREAD

**Issue by tempbottle** [yuankunzhang/charming#22]
doc is here:
[https://echarts.apache.org/en/option.html#series-line.label](https://echarts.apache.org/en/option.html#series-line.label)

can not add label for Line:
https://github.com/yuankunzhang/charming/blob/dbf7e05c58f5f6db0dbb0503cfcc665f8d041e34/examples/leptos-demo/src/main.rs#L20

**Comment by moinmoti** [comment]
Can we have a new release with this include?

**Comment by yuankunzhang** [comment]
This is published.
