### ISSUE TITLE
[feature request] Derive some useful traits

### ISSUE THREAD

**Issue by koopa1338** [yuankunzhang/charming#27]
I want to suggest deriving `Clone` and `PartialEq` for charts and containing structs. `Serialize` and `Deserialize` for example could also be feature gated, if necessary. What do you think?

**Comment by yuankunzhang** [comment]
Hi @koopa1338 , thanks for the suggestion. What are the justifications that we would want a chart to implement `Clone` and `PartialEq`?

**Comment by koopa1338** [comment]
When using leptos you are using a lot of move closures, which it makes a real hassle to make the chart responsive in leptos.

`PartialEq` may be an edge case and I only need it to detect if a chart has changed, maybe there is an api to catch those events?

In general, I would recommend deriving traits from the std if it doesn't hurt performance, and it makes sense, otherwise feature gate the derives.
