### ISSUE TITLE
Slice of a polar plot

### ISSUE THREAD

**Issue by structwafel** [yuankunzhang/charming#36]
Is there a possibility of only displaying half of a polar plot?
As I can't seem to be able to do so.

Something like so:
![2023-12-04_21-54](https://github.com/yuankunzhang/charming/assets/68999840/9355a9fe-9952-44b6-be74-d7d80be7a0c0)

**Comment by LukaOber** [comment]
Support for this was added in echarts version 5.5.0, we are currently using 5.4.2
I will try to create a PR soon-ish to upgrade to the new version.

**Comment by LukaOber** [comment]
If you are using the latest git version this will work now. In my PR I also attached a minimal example.
