### ISSUE TITLE
Polars Dataframe, ndarray and charming dataframe

### ISSUE THREAD

**Issue by wangjiawen2013** [yuankunzhang/charming#38]
Hi,
What are the differences between rust polars dataframe/ndarray and charming dataframe ? The polars and charming dataframe are both created with df! macro. Can I use polars/ndarray instead of charming dataframe ? If not, how to convert them to charming dataframe ?

**Comment by humphreylee** [comment]
Bumped with similar question.

**Comment by LukaOber** [comment]
They are completly seperate from another, they just have the same name. I don't think there is a general way to convert between them and it is up to you to do it. 
If you are trying to plot from polars you can also try [plotlars](https://github.com/alceal/plotlars)
