### ISSUE TITLE
JavaScript V8 engine 

### ISSUE THREAD

**Issue by sharkLoc** [yuankunzhang/charming#6]
The JavaScript V8 engine was too difficult to download during initial compilation, are there any other solutions?

**Comment by lcmgh** [comment]
Seems to be optional now? https://github.com/yuankunzhang/charming/commit/ac3751df5e7c631e8ef783696e0bebe134b0d0c5

**Comment by yuankunzhang** [comment]
If you don't need it to directly produce static images, you can exclude it by not enabling the `ssr` feature. You can use the `HtmlRenderer` to generate an HTML fragment and let your browser do the rendering, or you can use the `WasmRenderer` to render the charts in a WebAssembly environment.
