### ISSUE TITLE
use::charming::WasmRenderer

### ISSUE THREAD

**Issue by ngmisl** [yuankunzhang/charming#7]
I'm unable to use the renderer (and I can't find it anywhere else)

charming = { version = "0.1.2", feature = "wasm" }

But same for 0.2.1

```
error[E0432]: unresolved import `charming::WasmRenderer`
 --> src/main.rs:3:5
  |
3 | use charming::WasmRenderer;
  |     ^^^^^^^^^^------------
  |     |         |
  |     |         help: a similar name exists in the module: `HtmlRenderer`
  |     no `WasmRenderer` in the root
```

**Comment by yuankunzhang** [comment]
Hmm, that's weird, I have this Yew example working just fine - https://github.com/yuankunzhang/charming/blob/1738e15a1acaed6e998bf0697aaaa9cfeadf3be5/examples/yew-demo/src/main.rs#L2

Can you provide your main.rs source code so I can have a troubleshoot? Thanks.

**Comment by yuankunzhang** [comment]
The `ssr` feature and `wasm` feature are mutually exclusive, they can't be used together.

**Comment by ngmisl** [comment]
> The `ssr` feature and `wasm` feature are mutually exclusive, they can't be used together.

I'm getting the same when I remove the imagerenderer, if that's what you meant :)

**Comment by yuankunzhang** [comment]
I tried your code locally and it has no issue compiling -

![image](https://github.com/yuankunzhang/charming/assets/10398845/0bfde220-5a99-4cab-ad03-0d615f3578b4)

**Comment by Hpmason** [comment]
> charming = { version = "0.1.2", feature = "wasm" }

@ngmisl  In order to specific features in your `Cargo.toml`, you have to provide a *list* of strings using the ID `features`. It should look like this:
```toml
charming = { version = "0.2.1", features = ["wasm"]}
```

I think you forgot to use a list and also forgot to use the pluralize "features"

**Comment by ngmisl** [comment]
> > charming = { version = "0.1.2", feature = "wasm" }
> 
> @ngmisl In order to specific features in your `Cargo.toml`, you have to provide a _list_ of strings using the ID `features`. It should look like this:
> 
> ```toml
> charming = { version = "0.2.1", features = ["wasm"]}
> ```
> 
> I think you forgot to use a list and also forgot to use the pluralize "features"

thank you!
